# Deployment Configuration Script for Documake
# This script configures the application for production deployment using Waitress

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Documake Deployment Configuration" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check Python installation
Write-Host "Checking Python installation..." -ForegroundColor Green
try {
    $pythonVersion = python --version 2>&1
    Write-Host "Found: $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "Error: Python is not installed or not in PATH" -ForegroundColor Red
    Write-Host "Please install Python 3.8 or higher from python.org" -ForegroundColor Yellow
    exit 1
}

# Check if virtual environment exists
if (Test-Path "venv") {
    Write-Host "Virtual environment already exists." -ForegroundColor Yellow
    $response = Read-Host "Do you want to recreate it? (y/N)"
    if ($response -eq 'y' -or $response -eq 'Y') {
        Write-Host "Removing old virtual environment..." -ForegroundColor Yellow
        Remove-Item -Recurse -Force venv
    } else {
        Write-Host "Using existing virtual environment." -ForegroundColor Green
    }
}

# Create virtual environment if it doesn't exist
if (-not (Test-Path "venv")) {
    Write-Host "Creating virtual environment..." -ForegroundColor Green
    python -m venv venv
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Error: Failed to create virtual environment." -ForegroundColor Red
        exit 1
    }
}

# Activate virtual environment
Write-Host "Activating virtual environment..." -ForegroundColor Green
& .\venv\Scripts\Activate.ps1

# Upgrade pip
Write-Host "Upgrading pip..." -ForegroundColor Green
python -m pip install --upgrade pip --quiet

# Install requirements
Write-Host "Installing production dependencies..." -ForegroundColor Green
pip install -r requirements.txt

if ($LASTEXITCODE -ne 0) {
    Write-Host "Error: Failed to install requirements." -ForegroundColor Red
    exit 1
}

# Create production configuration file
Write-Host "Creating production configuration..." -ForegroundColor Green

$configContent = @"
# Production Configuration for Documake
# Generated by setup_deployment.ps1

# Server Configuration
HOST=0.0.0.0
PORT=8080
THREADS=4

# Flask Configuration
FLASK_ENV=production
SECRET_KEY=CHANGE-THIS-TO-A-RANDOM-SECRET-KEY-$(New-Guid)

# Database
DATABASE_PATH=paystub.db

# Logging
LOG_LEVEL=INFO
"@

$configContent | Out-File -FilePath "production.env" -Encoding UTF8
Write-Host "Created production.env configuration file" -ForegroundColor Green

# Create .env file if it doesn't exist
if (-not (Test-Path ".env")) {
    Copy-Item "production.env" ".env"
    Write-Host "Created .env file from production template" -ForegroundColor Green
    Write-Host "WARNING: Please update the SECRET_KEY in .env file!" -ForegroundColor Yellow
}

# Create logs directory
if (-not (Test-Path "logs")) {
    New-Item -ItemType Directory -Path "logs" | Out-Null
    Write-Host "Created logs directory" -ForegroundColor Green
}

# Check database initialization
Write-Host "Checking database..." -ForegroundColor Green
if (-not (Test-Path "paystub.db")) {
    Write-Host "Database will be created on first run." -ForegroundColor Yellow
} else {
    Write-Host "Database file exists." -ForegroundColor Green
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Deployment Configuration Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Review and update production.env with your settings" -ForegroundColor White
Write-Host "2. Update SECRET_KEY in .env file (IMPORTANT for security!)" -ForegroundColor White
Write-Host "3. Run the production server with: .\run_production.ps1" -ForegroundColor White
Write-Host ""
Write-Host "To activate the virtual environment manually:" -ForegroundColor Cyan
Write-Host "  .\venv\Scripts\Activate.ps1" -ForegroundColor White
Write-Host ""

